export * from './antecedentes-familiares.controller.js'
export * from './auth.controller.js'
export * from './especialista.controller.js'
export * from './estado-civil.controller.js'
export * from './paciente.controller.js'
export * from './rol.controller.js'
export * from './sexo.controller.js'
export * from './sucursal.controller.js'
